# Reference file : https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
run:
  timeout: 10m
  paths:
    exclude:
      - tests/**
linters-settings:
  tagalign:
    sort: false

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - sqlclosecheck # not relevant yet (SQL)
    - rowserrcheck # not relevant yet (SQL)
    - execinquery # not relevant yet (SQL)
    - cyclop # duplicate of gocyclo
    - lll # Not relevant
    - gocyclo # FIXME must be fixed
    - gocognit # Too strict
    - nestif # Too many false-positive.
    - prealloc # Too many false-positive.
    - makezero # Not relevant
    - dupl # Too strict
    - gosec # Too strict
    - gochecknoinits
    - gochecknoglobals
    - wsl # Too strict
    - nlreturn # Not relevant
    - gomnd # Too strict
    - stylecheck # skip because report issues related to some generated files.
    - testpackage # Too strict
    - tparallel # Not relevant
    - paralleltest # Not relevant
    - exhaustive # Not relevant
    - exhaustruct # Not relevant
    - goerr113 # Too strict
    - wrapcheck # Too strict
    - noctx # Too strict
    - bodyclose # too many false-positive
    - forcetypeassert # Too strict
    - tagliatelle # Too strict
    - varnamelen # Not relevant
    - nilnil # Not relevant
    - ireturn # Not relevant
    - contextcheck # too many false-positive
    - containedctx # too many false-positive
    - maintidx # kind of duplicate of gocyclo
    - nonamedreturns # Too strict
    - gosmopolitan  # not relevant
    - depguard # Not relevant for now as we don't have a list of blacklisted dependencies
    - gci # not relevant as go imports is already used
    - godot # not relevant as it only checks if the comment is ended in period or not.
    - gofumpt # not relevant as we use goimports
    - thelper # test case helper linter, not relevant
    - inamedparam # Named interface params

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: '(.+)_test.go'
      linters:
        - errcheck
        - funlen
        - usestdlibvars
        - thelper
        - errchkjson
        - goconst
        - testifylint
    - path: 'tests'
      linters:
        - thelper
        - testifylint

